In [1]:
import torch
src = torch.arange(1, 11)
src

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
src = src.reshape((2,5))
src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [3]:
index = torch.tensor([[3,1,2,0]])
index

tensor([[3, 1, 2, 0]])

In [4]:
torch.zeros(3,5, dtype=src.dtype).scatter_(1, index, src)

tensor([[4, 2, 3, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

# TORCH.TENSOR.SCATTER_

```python3
self[index[i][j][k]][j][k] = src[i][j][k]  # if dim == 0
self[i][index[i][j][k]][k] = src[i][j][k]  # if dim == 1
self[i][j][index[i][j][k]] = src[i][j][k]  # if dim == 2
```

**parameters** :
- dim(int) - the axis along which to index
- index(LongTensor) - the indices of elements to scatter. When empty, the operation returns self unchanged.
- src(Tensor or float) - the source element(s) to scatter.
- reduce(str,optional) - reduction operation to apply, can be either `add` or `multiply`.