In [95]:
import torch
import numpy as np

# Directly from data

In [96]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

# From numpy as array

In [97]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# From another tensor

In [98]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor :\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor :\n {x_rand}\n")

Ones Tensor :
 tensor([[1, 1],
        [1, 1]])

Random Tensor :
 tensor([[0.7168, 0.2881],
        [0.7479, 0.2454]])



# With random or constant values

In [99]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor :\n {rand_tensor}\n")
print(f"Ones Tensor :\n {ones_tensor}\n")
print(f"Zeros Tensor :\n {zeros_tensor}\n")

Random Tensor :
 tensor([[0.4325, 0.9117, 0.9443],
        [0.0463, 0.5651, 0.2679]])

Ones Tensor :
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor :
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



# Attributes

In [100]:
tensor = torch.rand(3,4)
print(f"Tensor shape:\n {tensor.shape}\n")
print(f"Data type:\n {tensor.dtype}\n")
print(f"Device:\n {tensor.device}\n")

Tensor shape:
 torch.Size([3, 4])

Data type:
 torch.float32

Device:
 cpu



# Operations on Tensors

In [101]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(f"Device:\n {tensor.device}\n")

Device:
 cuda:0



## standard numpy-like indexing and slicing

In [102]:
tensor = torch.ones(4,4)
print("First row of tensor: \n", tensor[0])
print("First column of tensor: \n",tensor[:,0])
print("Last column of tensor: \n",tensor[...,-1])

tensor[:,1] = 0
print("\n",tensor)

First row of tensor: 
 tensor([1., 1., 1., 1.])
First column of tensor: 
 tensor([1., 1., 1., 1.])
Last column of tensor: 
 tensor([1., 1., 1., 1.])

 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## Joining tensors

In [103]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [104]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## Arithmetic operations

In [105]:
# methods for matrix multiplication
method1_1 = t1@t1.T   # 4x12 @ (4x12).T = 4x4
method1_2 = t1.matmul(t1.T)

method1_3 = torch.rand(4,4)
torch.matmul(t1,t1.T,out=method3)

/tmp/ipykernel_53813/2260698137.py:6: UserWarning: An output with one or more elements was resized since it had shape [4, 12], which does not match the required output shape [4, 4].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:23.)
  torch.matmul(t1,t1.T,out=method3)


tensor([[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]])

In [106]:
# method for element-wise product
method2_1 = t1 * t1
method2_2 = t1.mul(t1)

method2_3 = torch.rand((t1*t1).shape)
torch.mul(t1,t1,out=method3)

/tmp/ipykernel_53813/2749157715.py:6: UserWarning: An output with one or more elements was resized since it had shape [4, 4], which does not match the required output shape [4, 12].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:23.)
  torch.mul(t1,t1,out=method3)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

# Single-element tensors
If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item()

In [107]:
agg = t1.sum()
print(agg)

agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(36.)
36.0 <class 'float'>


# Inplace operations
Operations that store the result into the **operand** are called in-place.
For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [108]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


**[NOTE]**

In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

# Bridge with numpy

In [109]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [110]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

np.add(n,1,out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


# NumPy array to Tensor

In [111]:
n = np.ones(5)
t = torch.from_numpy(n)
# Changes in the NumPy array reflects in the tensor.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
